name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python for backend
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          make install-backend

      - name: Start backend server
        run: |
          cd backend
          python manage.py runserver

      - name: Wait for the backend server to start
        run: |
          echo "Waiting for the server to start..."
          sleep 20  # Increase the wait time to 60 seconds


      - name: Check if backend server is running
        run: |
          curl --silent --fail http://localhost:8000/health/ || (echo "Server is not running!" && exit 1)
