name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python for backend
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          make install-backend

      - name: Start backend server
        run: |
          cd backend
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 8000 > server.log 2>&1 &
      

      - name: Wait for the backend server to start
        run: sleep 30  # Waits for 10 seconds

      - name: Output backend server logs
        run: cat backend/server.log


      - name: Check if backend server is running
        run: |
          curl --silent --fail http://localhost:8000/health/ || exit 1